### PR TITLE
Added ability to delete or rename Table Default

### PR DESCRIPTION
**Pull request by therealsujitk**
This pull request gives users the ability to rename **Table Default**, as shown here:

image

And delete this table if more than one table is available, as shown here:

image

Feature requested at #125

### CODE REVIEW

**Comment by vatz88** [comment]
Hey @therealsujitk thanks for taking this up!

Since there's no active FFCS going on, I'll review, test and merge it in my free time.

**Comment by therealsujitk** [comment]
@vatz88 cool, no prob. I know the issue was quite old, but it'll be better to link this pull request to that issue so that someone else doesn't open a duplicate pull request.

**Comment by vatz88** [comment]
@therealsujitk it's already linked as you have mentioned the issue number in the PR description

**Comment by therealsujitk** [comment]
I was talking about this:



But I guess mentioning the issue works too.

**Pull request merged**
