### PR TITLE
Added space in Course Name

### PR DESCRIPTION
**Pull request by C-Society**
Added Space in course name "VULNERABILITY ANALYSIS ANDPENETRATION TESTING".

### CODE REVIEW

**Comment by C-Society** [comment]
The \n is not working in the Desktop version.

image

**Comment by vatz88** [comment]
Hi @C-Society Thanks for the PR. I understand what you're trying to fix. But making changes directly to `all_data.json` file is not the correct way to do it. The `all_data.json` is generated as part of build process and not manually updated. Although the build process is not automated, it's better to do it the correct way. See the [util](https://github.com/vatz88/FFCSonTheGo/tree/master/util) folder for more details. What you should do is update the `report.xlxs` and then run `npm run convert`.

**Comment by C-Society** [comment]
Alright, I got it now. Will do it with the mentioned way.

**Comment by vatz88** [comment]
Closing this PR since FFCS for the forthcoming semester is over.

**Pull request closed without merging**
