### PR TITLE
Improved screenshots

### PR DESCRIPTION
**Pull request by therealsujitk**
image

image

### CODE REVIEW

**Review by vatz88 — APPROVED** [review]

**Comment by vatz88** [comment]
Thanks @therealsujitk This looks great! Sorry about delayed response, I'm on a vacation/ traveling. Will review your other PRs too

**Comment by therealsujitk** [comment]
@vatz88 no problem! Take your time, I think our FFCS registrations are over for this semester and these PRs are just improvements and bug fixes. Let me know if you need any changes to be made.

**Comment by vatz88** [comment]
@therealsujitk I tried on mobile and it seems screenshot is not working the 2nd time you try it. Can you please check

**Comment by therealsujitk** [comment]
@vatz88 I just checked, I was able to download both images multiple times. Can you give me steps to reproduce?

**Comment by vatz88** [comment]
On my phone it seems like if the table name is same it's not downloading again

**Comment by therealsujitk** [comment]
> On my phone it seems like if the table name is same it's not downloading again

:thinking: it could be because that OS is preventing multiple downloads thinking it already exisits, you use iOS? Android allows multiple downloads automatically renaming them. Is it the same if you make some change (like adding a course) and then download it with the same table name? Maybe if it compares binaries it'll understand it's not the same file.

**Pull request merged**
