### PR TITLE
Code refactoring on top of #179

### PR DESCRIPTION
**Pull request by vatz88**
Should automatically close #179 when merged.

### CODE REVIEW

**Comment by vatz88** [comment]
Hey @therealsujitk can you review/ test this PR.
This has all you commits, made one on top of those. Merging this will also merge you PR.

Some changes I did
- I removed code relating to dark mode, as it'll be dead code until we have dark mode finalized
- Made timetable take the full width, padding around if kinda waste of space. (Why I like this design? - as an example if you look at how design has evolved at facebook and instagram, they have removed the padding around images from the view so that images take full width, giving better view. Seems twitter is going to do the same for images in tweets)
- Used bootstrap card component for course panel
- some code refactoring as i felt right (feel free to point out any mistakes!)

**Comment by vatz88** [comment]
Haven't decided where to keep `grid` for courses buttons.
I think using bootstrap classes would be better than writing custom css. Plus using BS ensures better cross browser support.
In general I want to remove as much custom css code as possible and use BS over it

**Comment by vatz88** [comment]
also fontawesome unnecessarily increase the bundle size just for few icons we use. need to look into it

**Comment by therealsujitk** [comment]
> Used bootstrap card component for course panel

Not sure why I didn't come across this, but it looks great!

<hr>

> Made timetable take the full width, padding around if kinda waste of space. (Why I like this design? - as an example if you look at how design has evolved at facebook and instagram, they have removed the padding around images from the view so that images take full width, giving better view. Seems twitter is going to do the same for images in tweets)

In the case of images, both width and height are increased at the same ratio. But in this case it's only the width, having full width is unnecessary according to me. This is how it would look on a big monitor.

deploy-preview-181--ffcsonthego netlify app_

Because of this, I used smaller containers keeping everything even (including the navbar).

<hr>

The current navigation bar might need some adjusting, the campus dropdown isn't vertically aligned. You can check out browser support for `grid` at https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns.

I'm not a fan of this design, but I don't have much experience in making a user-friendly designs, so if you feel this is better, then I have no complaints.

I made a lot of improvements on top of #179 which can be viewed at [therealsujitk/cleanups-and-improvements](https://github.com/therealsujitk/FFCSonTheGo/tree/cleanups-and-improvements). However with all of these changes it's going to have several conflicts. Unfortunately I can't contribute as much anymore since I have some other work to attend to before college starts again, I've been able to contribute this much only because we're on summer break right now. I can open a PR, and if has too many conflicts then you can just close it or leave it open for later. Would you still like me to? If yes, let me know if I should open it before or after you merge either of the redesign PRs, if it's before then it'll include the redesign changes as well.

**Comment by vatz88** [comment]
> In the case of images, both width and height are increased at the same ratio. But in this case it's only the width, having full width is unnecessary according to me. This is how it would look on a big monitor.

Yes, will keep it in todo list. But for smaller screens, we can not have side margins or paddings.

> Unfortunately I can't contribute as much anymore since I have some other work to attend to before college starts again, I've been able to contribute this much only because we're on summer break right now.

Sure, no problem! Thanks for all the contributions so far. You can pick up as and when you get time. Cleaning up in itself is lot of work and has to be opinionated. Reviewing all the code in that case is also very time consuming for me. Didn't think it'll be this huge task initially until I started reviewing your PR. What I suggest is I'll take care of the clean up as and when I get time, you can add any new features you want on top of this like - better screenshots, dark mode, timetable in pdf in separate PR. Would be happy to merge.

You shouldn't have to resolve the conflicts, I know it's tedious, if you already have worked on new feature, just smartly copy paste those changes.

**Comment by vatz88** [comment]
keeping pr changes small helps to review it quicker and avoids complexity of resolving conflicts. So yeah try to break it down into as many independent PR as you can. My bad but I should have ask for that before. All the huge clean up doesn't have to go into one PR.

**Comment by vatz88** [comment]
No point in working on theme toggle button and until the toggle in working. I can't keep it in code because if it's never worked upon in future, it'll create confusion + is dead code.

Some other important points are
- we should avoid have custom break points, and only use bootstrap defined breakpoints
- jquery and bootstrap doesn't have to be added to global scope; need to fix dependencies which need them (added comment in the code). When this project was started, there was no parcel bundler and it was just added by script tag in html.

**Comment by vatz88** [comment]
@therealsujitk in your PR i see many changes which can be cherry-picked and be a separate PR in itself

For example, 
`Updated README.md 9602e6a8d65d75ab9651f34f274bfd6c63042ced` 
`Moved colours into a separate file 2fa2bde15a3985821a9d0481c0a974b5a15adac8`
`Moved js functions into separate files and removed redundant code 94acd33f7926215d78b962ef529d9ce364b3d6fc`

These separate PRs should easier to review and merge

Some changes as in like `Updated prettier config 3ffb918c6643c6b41a6a9b775038651d53972a7a`, I'd not want to merge because formatting config is a personal choice and there's not write or wrong unless there's a strong opinion on something. Some are my opinions at the time of write code but I'd rather want to stick to defaults of prettier and even remove my opinionated config. Defaults work better for everyone.

**Comment by therealsujitk** [comment]
> You can add any new features you want on top of this like - better screenshots, dark mode, timetable in pdf in separate PR. Would be happy to merge.

Alright! 

- The screenshot algorithm is already in the branch I linked above, since it's restructured it's very easy to find `/src/js/timetable.js`. Instead of opening everything in a new tab I open a modal where the user can choose whether to download the timetable or the course list.
- I've also improved the filter algorithm, brought it down to O(n) and added a Select All / Deselect All option. (Select All, maybe not useful, but Deselect All certainly is if the user wants to deselect everything)
- I've gotten rid of the double pipes (`|`) in the slot buttons and the  trailing hyphen (`-`) in the timetable when there's a field missing.
- I've added a `last-update` filed in the `package.json` file, so when you change the value of the field there, it'll reflect everywhere.
- The sorting algorithm wasn't very efficient, for some reason it was checking whether it was sorted in ascending order each time even though there are separate `ascending` and `descending` options. I improved it and added a third option. When the user clicks a column once, it sorts in ascending, the second time in descending, and the third time it'll go back to how it was (unsorted, or sorted according to the course id).
- Correct me if I am wrong, but adding a course to the course list has a bug, it checks whether the course list is sorted but always assumes it's in ascending order? So it would insert the course at the wrong position if it's in descending order. I fixed that code too, but didn't check if it was working before.
- Tables have a footer (`<tfoot></tfoot>`), that i didn't know about, I moved the total credits row there, that also solves the hover problem. (Note: there's other code in `course-list.js` changed because of this move, it made things easier).
- I added a bootstrap modal to be displayed when a new update is available, it'll revert back to the current one in-case bootstrap or jQuery wasn't found.

The `updateCredits()` function also isn't very efficient, I haven't changed it but I think it'll be better if you pass the course credits to it as an argument and it just adds (or subtracts) that value instead of doing it from scratch each time.

The highlight algorithm isn't exactly perfect, I tried logging it into the console whenever something is highlighted to see what was going on, and I noticed it adds classes to the array, but not necessarily the right ones, and when nothing is highlighted, it may still have something stored in the array. I didn't really understand how it worked but I left it as it is.

The `checkSlotClash()` function has some code that I didn't understand, like there were checks for whether a project is in the timetable, maybe it was different back then, or i still don't understand how VIT works.

I left these two untouched one because, I didn't understand it, it works, better not break it. Two, it'll have to be changed quite soon because of #169. After reading how you added classes like `no-pre-thoery` and `no-post-lab` to check for slot clashes, I realised when implementing timetables from a JSON shemea, we'll also have to use JavaScript's `Date` class to check for clashes, and that would be quite a pain.

If you get time, you can copy and paste anything from this branch, I have no problem with that.

> we should avoid have custom break points, and only use bootstrap defined breakpoints

Bootstrap doesn't only have the `container-fluid` class, you can check out their other classes at https://getbootstrap.com/docs/5.0/layout/containers/ where it's properly documented what screen size it will stop taking 100% width. If you see under `container-fluid`, it doesn't have a breakpoint.

> jquery and bootstrap doesn't have to be added to global scope

Previously there were several instances of jquery defined, that isn't good practice and would just load jquery multiple times for the client. But the main reason I made it global is because plugins such as `bootstrap` or `bootstrap-select` attach themselves to a jQuery instance. Suppose you localise jQuery and have multiple instances. The code might understand what to do when `$('#my-modal').modal();` is called in one file but not in another because `bootstrap` is only attached to the one where it works. This is why `bootstrap` requires `jquery` to be attached to the DOM window.

> Some changes as in like Updated prettier config `3ffb918c6643c6b41a6a9b775038651d53972a7a`, I'd not want to merge because formatting config is a personal choice and there's no right or wrong unless there's a strong opinion on something.

There wasn't anything wrong, prettier was breaking if statements even though they weren't that big, and in some cases it has harder to read, so I increased it to 100.

**Comment by vatz88** [comment]
> Suppose you localise jQuery and have multiple instances

I don't think so, to best of my knowledge that's not how bundlers work. You can import a package in as many files you want and it should give you the same instance as opposed to creating different instances in each file you have imported it. I'll may be still test it out

**Comment by therealsujitk** [comment]
> I don't think so, to best of my knowledge that's not how bundlers work. You can import a package in as many files you want and it should give you the same instance as opposed to creating different instances in each file you have imported it. I'll may be still test it out

I actually got an error with `bootstrap-select` because it was localised. Suppose you import `jquery` and `bootsrtap-select` in `course-panel.js` and you import `jquery` in another say `timetable.js`, `bootstrap-select` was only attached to the `jquery` instance in `course-panel.js`, it's functions were not defined in `timetable.js`. After looking at StackOverflow, someone wrote it's best to attach it to the window. I believe the current version in prod has local as well as an instance attached to window, so it's finding a way to work.

Attached to the window: https://github.com/vatz88/FFCSonTheGo/blob/master/src/js/main.js#L5
Local instance: https://github.com/vatz88/FFCSonTheGo/blob/master/src/js/autocomplete_course.js#L1
Local instance: https://github.com/vatz88/FFCSonTheGo/blob/master/src/js/color_change.js#L1

Bootstrap requires (or atleast did before bootstrap 5) jQuery to be attached to the window because it has to be used in `index.html`. And if it's already attached to the window, importing them again isn't necessary. Since it gave me the error I mentioned above, I assumed it must be creating a new instance every time or atleast the DOM window made a copy for itself, either of these would explain it.

**Comment by therealsujitk** [comment]
> Correct me if I am wrong, but adding a course to the course list has a bug, it checks whether the course list is sorted but always assumes it's in ascending order? So it would insert the course at the wrong position if it's in descending order. I fixed that code too, but didn't check if it was working before.

This is broken in production as well btw, you can test it out.

**Comment by vatz88** [comment]
`bootstrap-select` is probably expecting reference to jquery on `window` (so i'm still adding it to window as a hack until we do something better) but yes, importing a package to multiple files would still give you the same instance/reference.

**Comment by vatz88** [comment]
> > Correct me if I am wrong, but adding a course to the course list has a bug, it checks whether the course list is sorted but always assumes it's in ascending order? So it would insert the course at the wrong position if it's in descending order. I fixed that code too, but didn't check if it was working before.
> 
> This is broken in production as well btw, you can test it out.

We can call it bug. On sorted list it seems to append on the end of the list and not at the correct position but if you click the header it'll sort correctly. Is this what you're saying? If you have already a fixed it, you can raise a PR. Some good samaritan like you had contributed to add that sorting feature :D

**Pull request merged**
