### PR TITLE
Minor Improvements & Code Cleaning

### PR DESCRIPTION
**Pull request by rishabhkumardeveloper**
Worked on Minor Improvements & Code Cleaning.
Fixed the Whatsapp share button (Now works for both Mobile & PC).
Added share option using native sharing mechanism of the device.
Organized the JavaScript & SCSS into different components, for better understanding.
Organized major components (Ex. Time Table) into folders.
Issue No #193

### CODE REVIEW

**Comment by vatz88** [comment]
Hey @rishabhkumardeveloper thanks for you efforts in making contribution to this repo.
I'm keeping really busy since last few weeks. So it'll take a while before I can review. There are bunch of other open PRs too I need to review.

Hey @therealsujitk if possible can you please review this PR, considering you also have some ideas on refactoring.

**Comment by therealsujitk** [comment]
> Hey @therealsujitk if possible can you please review this PR, considering you also have some ideas on refactoring.

Sure! I'll take a look as soon as I can.

**Comment by rishabhkumardeveloper** [comment]
@therealsujitk , The 'Share Using' Option has been built using Navigator.share() function. Chromium based browsers support it. It has mainly been built for Mobile devices, wherein, the users can share the website using a variety of options natively belonging to the OS. 

On the SCSS side, I realized that certain rules are in the wrong file. I'll definitely correct the same. 

For the JS Side, I've moved certain functions into different files.It's just a start to organization of the project. I myself wanted to separate out all the functions pertaining to a certain component (ex. time table) into it's own set of files or folders. However, due to the fact that there are multiple dependencies between functions, it was getting hard to separate it completely. The code seemed to stop working on further separation. I would certainly work on this further. 

I would also delete package-lock.json, thank you for pointing that out. 

I have understood the code base much better & hope to meaningfully contribute in the following days.

**Comment by therealsujitk** [comment]
> The 'Share Using' Option has been built using Navigator.share() function. Chromium based browsers support it. It has mainly been built for Mobile devices, wherein, the users can share the website using a variety of options natively belonging to the OS (Android/IOS).

Not everyone is going to be using Chromium based browsers, moreover I tested it on Brave (a Chromium browser) and it refreshed the page. And if it only works on Android & iOS, then it has to be removed on on other platforms.

> For the JS Side, I've moved certain functions into different files.It's just a start to organization of the project. I myself wanted to separate out all the functions pertaining to a certain component (ex. time table) into it's own set of files or folders. However, due to the fact that there are multiple dependencies between functions, it was getting hard to separate it completely. The code seemed to stop working on further separation. I would certainly work on this further.

I have organised the SCSS and JS files in my [`cleanups-and-improvements`](https://github.com/therealsujitk/FFCSonTheGo/tree/cleanups-and-improvements) branch, however this was for an older version and hence couldn't be merged as it had too many conflicts. You can refer to that and see how I have organised the functions and rules. There are also several functions and rules that are no longer relevant and need to be removed.

Lastly, if possible it would be great if you could separate it into two PRs, one that separates the SCSS files and another that separates the JS files. This would also make it easier for @vatz88 to review.

**Comment by rishabhkumardeveloper** [comment]
@therealsujitk , Alright. I'll remove the Native Sharing option from the other platforms. We can use a separate PR for the same. 

I would definitely go through your code to understand the organization & make apt changes. I'll also try to remove more irrelevant functions. 

Once, I'm done with the additional changes, we can work with two separate PR's for SCSS & JS.

**Comment by vatz88** [comment]
Hey @rishabhkumardeveloper still working on this one? Large PRs are difficult for me to review and merge. If you and @therealsujitk can work it out together and test things as well. I can may be blindly merge it.

It's been more than 5yrs me running this project. I completed my studies in 2018 and have no touch with VIT now. If you guys are interested and want to work on this project, I can give you the code ownership and you can maintain and decide the future of this site. It's getting difficult for me to maintain. @therealsujitk would you be interested in being code owner?

I don't want to abandon it because thousands of students still use it!

**Comment by therealsujitk** [comment]
Yeah sure! I'd be happy to do it. I'll be sure to maintain this repository properly to ensure students don't face any issues.

**Comment by therealsujitk** [comment]
Since #208 has been merged, I'll be closing this PR.

**Pull request closed without merging**
