### PR TITLE
Update Course list for Chennai

### PR DESCRIPTION
**Pull request by syedomar1**
- I have updated the Course list for Winter semester 2023-24

### CODE REVIEW

**Comment by syedomar1** [comment]
@vatz88 Please do review the changes made to the file

**Comment by therealsujitk** [comment]
Will get to this as soon as #231 is resolved.

**Comment by therealsujitk** [comment]
@syedomar1, kindly update the [`chennai`](https://github.com/vatz88/FFCSonTheGo/blob/master/package.json#L6) semester field in the package.json as well.

**Comment by vatz88** [comment]
@syedomar1 can you also add video (maybe use [loom](https://www.loom.com/looms/videos)?) testing the changes, so we can be sure this doesn't break anything

**Comment by therealsujitk** [comment]
This seems fine other than some of the course names being cut short, which shouldn't be an issue. There's one other thing though, there are some courses with slots I've never seen before 🤔.

Screenshot 2023-10-31 at 02 29 55

**Comment by vatz88** [comment]
> some of the course names being cut short

Probably due to pdf to excel conversion. We need better PDF to excel converters

**Comment by syedomar1** [comment]
Sure, will look onto it.

**Comment by syedomar1** [comment]
It was a fault in the pdf from their end..
I have made the required changes.
@therealsujitk @vatz88 Please do review it if anything else needs to be done._

**Comment by vatz88** [comment]
Thanks @syedomar1 🙌
I'll let @therealsujitk review, verify and merge

**Comment by therealsujitk** [comment]
@syedomar1 there are still some slots that are not present in the current timetable (Ex: M3, N4, SC).

Screenshot 2023-10-31 at 13 05 09

The [`chennai.json`](https://github.com/vatz88/FFCSonTheGo/blob/master/src/schemas/chennai.json) schema will need to be updated with the newest timetable.

Most of the other issues have been fixed, for future reference, what converter did you use?

**Comment by syedomar1** [comment]
I haven't heard of those slots either. Those aren't slots for UG courses I believe. We can ignore those rows in the sheet, or do you want it removed?
I used this website https://xodo.com/pdf-to-excel-converter

**Comment by therealsujitk** [comment]
You can leave them. It won't really break the site, those slots will just be treated as `NIL`. @vatz88 I think this should be fine for now since we don't have the timetable to deal with these slots and we don't want to delay this for students. What do you think?

**Review by therealsujitk — APPROVED** [review]
LGTM (almost).

Schema will have to be updated with the new timetable ASAP. Will wait for feedback from @vatz88 before merging.

**Comment by therealsujitk** [comment]
@syedomar1 when is your course registration?

**Comment by syedomar1** [comment]
This Saturday and Sunday

**Comment by vatz88** [comment]
Do as it feels right to you 😄 , if merging makes more sense go ahead!


> Schema will have to be updated with the new timetable ASAP

What does it mean? Are we saying that Chennai is using a different timetable than the current on on our site?
If Vellore and Chennai use different timetables, we can't update it?

**Comment by therealsujitk** [comment]
Yeah, Chennai might have made changes to the timetable (yet again). Vellore and Chennai can have different timetables and we can still make it work because we have defined [schemas](https://github.com/vatz88/FFCSonTheGo/tree/master/src/schemas) for each campus. This just needs to be updated for Chennai when we get the timetable.

**Pull request merged**
