### PR TITLE
Updated the Courses and Slots

### PR DESCRIPTION
**Pull request by hariketsheth**
Have added the CHY1701 : Engineering Chemistry Course
- Added the Embedded Theory Slots Along with Faculties
- Added the Embedded Lab Slots Along with the Faculties 
(* Updated in Accordance with the slots available for the Winter Semester 2020-21)

Added Faculty for the MAT2002 : ADDE Course

### CODE REVIEW

**Comment by vatz88** [comment]
Hey @hariketsheth thanks for making efforts to contribute!

I see you have changed the slot names and timings. Is there a new timetable? Are these changes only for Chennai campus? If they're only for Chennai it'd break it for Vellore campus. If the timetable for both the campuses is different, we need a way to support different timetables for both the campuses.

@sanket9918 can you please help verify these changes for Vellore campus

**Comment by hariketsheth** [comment]
> Hey @hariketsheth thanks for making efforts to contribute!
> 
> I see you have changed the slot names and timings. Is there a new timetable? Are these changes only for Chennai campus? If they're only for Chennai it'd break it for Vellore campus. If the timetable for both the campuses is different, we need a way to support different timetables for both the campuses.
> 
> @sanket9918 can you please help verify these changes for Vellore campus

Yes, For Chennai, the Slots as well as timings are changed. 
I am not sure about the Vellore Campus though. 

I will try to update the course list as well since I see for the Chennai campus, Courses and faculties aren't added.

**Comment by vatz88** [comment]
@hariketsheth 
Can you try updating the code in a way that we can support different timetables for both campuses? We can't merge this PR until then because it'll break the timetable for Vellore.

Go through the code and give it a try. Share the approaches you have and I can may be guide you in that how we can add this support.

**Comment by sanket9918** [comment]
As per my knowledge and community discussions , we don't have any such change for Vellore Campus as of now. There maybe any change later as the next FFCS approaches. 

> Hey @hariketsheth thanks for making efforts to contribute!
> 
> I see you have changed the slot names and timings. Is there a new timetable? Are these changes only for Chennai campus? If they're only for Chennai it'd break it for Vellore campus. If the timetable for both the campuses is different, we need a way to support different timetables for both the campuses.
> 
> @sanket9918 can you please help verify these changes for Vellore campus

As per my knowledge and community discussions , we don't have any such change for Vellore Campus as of now. There maybe any change later as the next FFCS approaches.

**Comment by sanket9918** [comment]
> Hey @hariketsheth thanks for making efforts to contribute!
> 
> I see you have changed the slot names and timings. Is there a new timetable? Are these changes only for Chennai campus? If they're only for Chennai it'd break it for Vellore campus. If the timetable for both the campuses is different, we need a way to support different timetables for both the campuses.
> 
> @sanket9918 can you please help verify these changes for Vellore campus

As per my knowledge and community discussions , we don't have any such change for Vellore Campus as of now. There maybe any change later as the next FFCS approaches.

**Pull request closed without merging**
