### PR TITLE
Fixes and Ability to Store Multiple Tables Offline

### PR DESCRIPTION
**Pull request by sangeeth96**
**NOT READY TO BE PULLED INTO YET!**  

ffcsotg_newf

## What This Breaks
+ Might break the collapsing of top button row since I undid the CSS styles because they were messing with the default Bootstrap styles.

## Bugs To Fix
+ [x] Undesired course deleted

## Remaining Functionality
+ [x] Deleting existing tables.
+ [ ] Add option to name tables.
+ [ ] Fix the layout issue.
+ [ ] Style the '+' button.

### CODE REVIEW

**Comment by VaTz88** [comment]
Check out the PR https://github.com/sangeeth96/VIT-Time-Table-Visualizer/pull/1

It fixes the collapse of option buttons.

**Comment by sangeeth96** [comment]
I don't think we should add the "+" button to the dropdown. That's adding one extra step to access that feature. The dropdown be solely for accessing existing tables and yes, deleting them which is yet to be implemented. Leaving the button where it is means someone can quickly add one more table without having to go and open up the thing.

**Comment by VaTz88** [comment]
I agree but I find the 'add timetable' option in drop-down more better implementation. As far as the extra step I concerned we can have the drop-down to open on hover instead of clicking.

**Comment by sangeeth96** [comment]
It's still more movement. On what universe is it better to add it to the dropdown? What if there's 10 tables? How much would you have to move the cursor or scroll the screen to find the add button? 😐

**Comment by VaTz88** [comment]
Don't know why I have that kind of image in my mind that add button is better in drop-down. But we'll have as you say.

I was thinking if we can allow user to name the added timetable. Like 'morning', 'evening', etc. instead of generic names like 'Table 1', 'Table 2', etc.
That'll be easy to remember for switching and also when user resumes back later sometime.

**Comment by sangeeth96** [comment]
I thought about it but what I initially did was using an array for storing everywhere instead of converting it to another form like you initially did and then went on with that. Definitely possible and will add that to the list.

**Comment by VaTz88** [comment]
### Bug - Undesired course deleted

peek 2017-06-23 14-04

I think the bug is because of `var courseId = activeTable.data.length - 1;` here `activeTable.data.length` does not remain unique and value is repeated as any course is deleted and added.

**Comment by sangeeth96** [comment]
You're right. Now I get why you used two different DS before. 😝 I believe the same issue will be present in the table deletion because I used array indexes there too. Hm... One way would be to bring back the object/array combo or use `Map` I guess to maintain the ordering as well. I will work on this.

**Comment by sangeeth96** [comment]
Or we could just update the IDs once again but that's costly.

**Comment by sangeeth96** [comment]
Okay, made the following changes:
+ Fixed [the bug](https://github.com/VaTz88/FFCSonTheGo/pull/33#issuecomment-310607995). `courseId` is stored along with the course details and every new course is basically `lastCourseId + 1`. This ensures there's no duplicate values.
+ *Added support for deleting tables.* This also now increments `tableId`s based on the `lastTableId`.

**Comment by VaTz88** [comment]
I can't merge this PR unless you merge https://github.com/sangeeth96/VIT-Time-Table-Visualizer/pull/1 because there other changes I have pushed to it.

**Comment by VaTz88** [comment]
Merged https://github.com/VaTz88/FFCSonTheGo/commit/6194567fc83f0f9f6cb1cd4aaf9fd08cbb789e49

**Pull request closed without merging**
