### PR TITLE
Update Course list for Chennai

### PR DESCRIPTION
**Pull request by syedomar1**
I have updated the Course list for Fall semester 2024-25.

@therealsujitk @vatz88  Please do review the changes made in the file with the same format.

### CODE REVIEW

**Comment by therealsujitk** [comment]
Hey @syedomar1, thanks for this PR! Seems like there are a few issues with the uploaded `.xlsx` file, some slot strings are cut short. Can you see if you can fix them?

Screenshot 2024-06-26 at 23 21 31

**Comment by syedomar1** [comment]
@therealsujitk Thanks for noticing that and letting me know..
It was a fault in the pdf itself and I have resolved that issue.

**Comment by vatz88** [comment]
Thanks for the PR @syedomar1 !

I'd say please test this thoroughly before merging @syedomar1 @therealsujitk

**Comment by therealsujitk** [comment]
> @therealsujitk Thanks for noticing that and letting me know.. It was a fault in the pdf itself and I have resolved that issue.

I can still see the same issues 2087, 2092, 2093, 2106 - 2109. There records don't seem right to me. Maybe use a different pdf to xlsx converter or maybe share the PDF file here so one of us can try converting it.

**Comment by syedomar1** [comment]
@therealsujitk I have rectified the error by correcting the slots.
I have also added pdf file for your reference. It's a mistake in the pdf itself.

**Comment by therealsujitk** [comment]
@syedomar1, this looks good. Could you check the report uploaded in #249 and let me know if it's the same one? It seems to have some differences but I'm not fully sure.

**Comment by syedomar1** [comment]
@therealsujitk As of today (27/06) 7:30pm IST they have updated the file on VTOP. Even then it doesn't match with report in #249. 
I have uploaded the updated sheets by looking at each field properly and removed the pdf.
Please do review it.

**Review by therealsujitk — APPROVED** [review]
LGTM.

**Comment by therealsujitk** [comment]
@syedomar1 thankyou so much for your contribution! I don't want to delay this too much either or it'll get merged after your FFCS 😅, I'll merge it now 🚀!

**Comment by syedomar1** [comment]
@therealsujitk Thank you! Yeah truee..😂

**Comment by therealsujitk** [comment]
@syedomar1 could you share an image of the timetable the Chennai campus is currently using? Maybe during your mock or actual FFCS. We're trying to add unit tests for validating `.xlsx` files, and are missing the following slots in our schema.

Screenshot 2024-06-27 at 23 10 52

**Comment by syedomar1** [comment]
Sure..
We use this timetable.
tt5thsem

I think it's just that there so many random courses in the list they give.. Not sure for which course it is like PG or something and if they follow some other tt..

**Pull request merged**
